name: 🚀 Deploy IT Admin API

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            BRANCH="${{ github.ref_name }}"

            if [ "$BRANCH" = "main" ]; then
              PORT=9040
            elif [ "$BRANCH" = "staging" ]; then
              PORT=9041
            else
              echo "Unsupported branch"
              exit 1
            fi

            APP_DIR="/www/wwwroot/it-inventory-management"

            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/jhsassociatesllp/IT-Inventory-Management.git $APP_DIR
            fi

            cd $APP_DIR

            git fetch --all
            git reset --hard origin/$BRANCH

            echo "🛑 Stop old containers"
            APP_PORT=$PORT docker compose down --remove-orphans

            echo "🚀 Start new containers"
            APP_PORT=$PORT \
            MONGO_URI=${{ secrets.MONGO_URI }} \
            MONGO_DB=${{ secrets.MONGO_DB }} \
            docker compose up -d --build --force-recreate
            